language: ruby
sudo: false
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - CODECLIMATE_REPO_TOKEN=d42df0d47d387f23796b689cd7d196f0c6b5f1ce70b907ffdd9138c55c900600 bundle exec rspec
  - bundle exec codeclimate-test-reporter
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
